### ISSUE TITLE
Can't downgrade from 5100 (bounty)

### ISSUE THREAD

**Issue by non-bin** [ffmwheel/rewheel-main#3]
I have a 5314 pint, which I had 5040 running on. I updated to 5100 because I was curious, and now when I try to downgrade with ffmwheel it times out.
It will connect in live mode, and I can change ride modes and light state, but if I leave it for 10 seconds, the board cuts the connection. It stays connected, but everything reports as 0V, 0A, no ride modes, and doesn't react to light state changes.
Firmware update just sits for a second then fails, and the dev console reports a timeout.
Is there a way to force it into bootloader mode?

I'll give US$200 to whoever implements custom shaping and increased top speed on 5100.

**Comment by non-bin** [comment]
Completed, or not possible?

**Comment by non-bin** [comment]
Sorry @LeagueRaINi @ffmwheel, My board was in the shop for a ghosting issue. Yes, I still can't downgrade, there's been no change.

**Comment by non-bin** [comment]
Alright I can't do it, I don't understand React well enough. Can anyone impliment this?

```JS
const keepAliveFunction = () => {
  const { firmwareRevision, writeFirmwareRevision } = useBLECharacteristic("firmwareRevision", {
    read: true,
    write: true,
    notify: true,
  })

  buffer = new Uint16Array(2)
  view = new DataView(buffer)
  view.setUint16(0, firmwareRevision.getUint16())
  writeFirmwareRevision(view)
}

const onDisconnect = () => {
  clearInterval(window.keepAlive)
}

const onConnect = () => {
  clearInterval(window.keepAlive)
  keepAliveFunction()
  window.keepAlive = setInterval(keepAliveFunction, 10000)
}
```

**Comment by LeagueRaINi** [comment]
The official app writes 0x00 to speed rpm for the keep alive, also check out our tool http://owtk.pages.dev

**Comment by non-bin** [comment]
@LeagueRaINi I think any write anywhere is enough to keep the connection up. I ran your tool and it reportedly succeeded, but there's been no change. Has anyone ever managed to downgrade from 5100?

**Comment by LeagueRaINi** [comment]
> @LeagueRaINi I think any write anywhere is enough to keep the connection up. I ran your tool and it reportedly succeeded, but there's been no change. Has anyone ever managed to downgrade from 5100?

Probably but writing to the firmware characteristic has actual logic on the board so it's probably best to write to something that doesn't
As for our tool it only auths, so ideally u setup rewheel to flash right away after running our tool cause Auth expires after a few seconds like u already figured out with the app

**Comment by non-bin** [comment]
> As for our tool it only auths

oh right, that's cool, so I don't have to use the official app. I'll try once more but I don't think I'm quick enough, or there's somthing we're missing that's stopping it from flashing

**Comment by non-bin** [comment]
FUCK YEAH I GOT IT

thank you @LeagueRaINi, I wasn't kidding about the $100 if you want it, email me at jacka.alice@gmail.com

**Comment by LeagueRaINi** [comment]
> FUCK YEAH I GOT IT
> 
> thank you @LeagueRaINi, I wasn't kidding about the $100 if you want it, email me at [jacka.alice@gmail.com](mailto:jacka.alice@gmail.com)

nice glad you go it working, happy modding :)
